# _config.yml
title: My GitHub Pages Blog
description: A simple blog powered by Jekyll with Gitalk comments.
url: "https://LeakBox.github.io"  # 替换为你的站点 URL
permalink: /:year/:month/:day/:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
gitalk:
  repo: "LeakBox.github.io"  # 替换为你的仓库名，例如 "yourusername.github.io"
  owner: "LeakBox258"   # 替换为你的 GitHub 用户名
  admins: ["LeakBox258"]  # 管理员用户名