# _config.yml
title: My GitHub Pages Blog
description: A simple blog powered by Jekyll with Gitalk comments.
url: "https://Leakbox258.github.io"
permalink: /:year/:month/:day/:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
gitalk:
  repo: "Leakbox258.github.io"
  owner: "LeakBox258"
  admins: ["LeakBox258"]